title: "Judit Fischer" # the name of your site, e.g. ACME Corp.
exclude: ['README.md']
url: "juditfischer.com"

collections:
  posts:
    output: true
    sidebar_label: News
  projects:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "my-site"
  -
    scope:
      path: ""
      type: "projects" # previously `page` in Jekyll 2.2.
    values:
      layout: "project" # overrides previous default layout
      gallery:
        - image: "-image path-"
          caption: "--caption--"
