---
title: Judit Fischer
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/:name"
  uploads:
    title: Uploads
    output: true
exclude:
- README.md
url: juditfischer.com
permalink: pretty

defaults:
  - scope:
      type: "projects"
    values:
      layout: default
      title: --Title--
      gallery:
        - image: http://placekitten.com/200/300
          description: ""
    
